import j1 from "@/public/jobImage/j1.png";
import j2 from "@/public/jobImage/j2.png";
import j3 from "@/public/jobImage/j3.png";
import j4 from "@/public/jobImage/j4.png";

export const demoData = [
  {
    id: "1",
    full_name: "Leslie Alexander",
    email_address: "felicia.reid@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882918803",
    createdAt: "2014-05-30T00:00:00Z",
    time: "2014-05-30T10:30:00Z",
    additional_information: "Website",
    status: "Pre Application",
    image_name: j1,
  },
  {
    invoiceId: "5833",
    full_name: "Devon Lane",
    email_address: "bill.sanders@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+18102458249",
    createdAt: "2015-05-27T00:00:00Z",
    time: "2015-05-27T14:15:00Z",
    additional_information: "Phone Call",
    status: "Applied",
    image_name: j2,
  },
  {
    id: "3",
    full_name: "Eleanor Pena",
    email_address: "georgia.young@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882918803",
    createdAt: "2012-02-11T00:00:00Z",
    time: "2012-02-11T09:00:00Z",
    additional_information: "Facebook",
    status: "Pre Application",
    image_name: j3,
  },
  {
    id: "4",
    full_name: "Kathryn Murphy",
    email_address: "jessica.hanson@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14884608141",
    createdAt: "2014-01-14T00:00:00Z",
    time: "2014-01-14T16:45:00Z",
    additional_information: "Email",
    status: "Applied",
    image_name: j4,
  },
  {
    id: "5",
    full_name: "Robert Fox",
    email_address: "nathan.roberts@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882634865",
    createdAt: "2014-08-30T00:00:00Z",
    time: "2014-08-30T11:20:00Z",
    additional_information: "WhatsApp",
    status: "Pre Application",
    image_name: j1,
  },
  {
    id: "6",
    full_name: "Ronald Richards",
    email_address: "tanya.hill@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14884145917",
    createdAt: "2016-09-18T00:00:00Z",
    time: "2016-09-18T13:30:00Z",
    additional_information: "Website",
    status: "Pending",
    image_name: j2,
  },
  {
    id: "7",
    full_name: "Bessie Cooper",
    email_address: "kenzi.lawson@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+19143008346",
    createdAt: "2013-12-10T00:00:00Z",
    time: "2013-12-10T08:00:00Z",
    additional_information: "Referral",
    status: "Pre Application",
    image_name: j3,
  },
  {
    id: "8",
    full_name: "Cameron Williamson",
    email_address: "willie.jennings@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14882634869",
    createdAt: "2013-10-08T00:00:00Z",
    time: "2013-10-08T15:45:00Z",
    additional_information: "Instagram",
    status: "Pre Application",
    image_name: j4,
  },
  {
    id: "9",
    full_name: "Wade Warren",
    email_address: "dolores.chambers@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882820363",
    createdAt: "2013-07-27T00:00:00Z",
    time: "2013-07-27T10:30:00Z",
    additional_information: "Email",
    status: "Inactive",
    image_name: j1,
  },
  {
    id: "10",
    full_name: "Ralph Edwards",
    email_address: "nevaeh.simmons@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+18102448985",
    createdAt: "2017-08-16T00:00:00Z",
    time: "2017-08-16T14:20:00Z",
    additional_information: "Website",
    status: "Applied",
    image_name: j4,
  },
  {
    id: "11",
    full_name: "Marvin McKinney",
    email_address: "tim.jennings@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+19143008184",
    createdAt: "2016-09-23T00:00:00Z",
    time: "2016-09-23T09:15:00Z",
    additional_information: "Phone Call",
    status: "Pre Application",
    image_name: j2,
  },
];

export const candidateListData = [
  {
    id: "1",
    full_name: "Bessie Cooper",
    email_address: "felicia.reid@example.com",
    mobile_number: "+14842918883",
    position: "Nanny, House Manager",
    last_login: "2024-10-24T08:00:00Z",
    location: "Chicago",
    status: "Application Started",
  },
  {
    invoiceId: "5833",
    full_name: "Marvin McKinney",
    email_address: "bill.sanders@example.com",
    mobile_number: "+16102458249",
    position: "Baby/Night Nurse",
    last_login: "2024-10-24T08:05:00Z",
    location: "Other Locations",
    status: "Applied",
  },
  {
    id: "3",
    full_name: "Brooklyn Simmons",
    email_address: "georgia.young@example.com",
    mobile_number: "+14842918653",
    position: "Nanny",
    last_login: "2024-10-24T08:10:00Z",
    location: "Chicago, DC Metro Area",
    status: "Interview Complete",
  },
  {
    id: "4",
    full_name: "Courtney Henry",
    email_address: "jessica.hanson@example.com",
    mobile_number: "+14844080141",
    position: "Nanny",
    last_login: "2024-10-24T08:15:00Z",
    location: "DC Metro Area, Other Locations",
    status: "Application Started",
  },
  {
    id: "5",
    full_name: "Arlene McCoy",
    email_address: "nathan.roberts@example.com",
    mobile_number: "+14842634655",
    position: "Nurse",
    last_login: "2024-10-24T08:20:00Z",
    location: "DC Metro Area, Other Locations, New York, Chicago",
    status: "Profile Complete",
  },
  {
    id: "6",
    full_name: "Floyd Miles",
    email_address: "tanya.hill@example.com",
    mobile_number: "+14844145917",
    position: "Nanny",
    last_login: "2024-10-24T08:25:00Z",
    location: "Chicago",
    status: "Applied",
  },
  {
    id: "7",
    full_name: "Cody Fisher",
    email_address: "kenzi.lawson@example.com",
    mobile_number: "+18143008346",
    position: "House Manager",
    last_login: "2024-10-24T08:30:00Z",
    location: "Chicago",
    status: "Application Started",
  },
  {
    id: "8",
    full_name: "Jerome Bell",
    email_address: "willie.jennings@example.com",
    mobile_number: "+14842634689",
    position: "Nanny",
    last_login: "2024-10-24T08:35:00Z",
    location: "DC Metro Area, Other Locations",
    status: "Application Started",
  },
  {
    id: "9",
    full_name: "Guy Hawkins",
    email_address: "dolores.chambers@example.com",
    mobile_number: "+15552826353",
    position: "Nanny",
    last_login: "2024-10-24T08:40:00Z",
    location: "Chicago",
    status: "Applied",
  },
  {
    id: "10",
    full_name: "Kristin Watson",
    email_address: "nevaeh.simmons@example.com",
    mobile_number: "+16102449865",
    position: "Nanny, House Manager",
    last_login: "2024-10-24T08:45:00Z",
    location: "DC Metro Area, Other Locations",
    status: "Profile Complete",
  },
  {
    id: "11",
    full_name: "Esther Howard",
    email_address: "tim.jennings@example.com",
    mobile_number: "+18143008184",
    position: "Nanny, House Manager, Baby/Night Nurse",
    last_login: "2024-10-24T08:50:00Z",
    location: "DC Metro Area, Other Locations, New York, Chicago",
    status: "Application Started",
  },
];

export const statuse = [
  {
    value: "Pre Application",
    color: "bg-green-500/15 text-green-600",
  },
  {
    value: "Applied",
    color: "bg-purple-500/15 text-purple-600",
  },
  {
    value: "Inactive",
    color: "bg-red-500/15 text-red-600",
  },
  {
    value: "Pending",
    color: "bg-orange-500/15 text-orange-600",
  },
];

export const applicationDateOptions = [
  {
    value: "application_date",
    label: "Application Date",
  },
  {
    value: "last_login",
    label: "Last Login Date",
  },
  {
    value: "recent_access",
    label: "Recent Access",
  },
];

export const typeFilters = [
  {
    value: "midwest_elite_nannies",
    label: "Midwest Elite Nannies",
  },
  {
    value: "admin",
    label: "ADMIN",
  },
  {
    value: "user",
    label: "USER",
  },
];

export const locationFilters = [
  {
    value: "dc_metro",
    label: "DC Metro Area",
  },
  {
    value: "new_york",
    label: "New York",
  },
  {
    value: "miami",
    label: "Miami",
  },
  {
    value: "iowa",
    label: "Iowa",
  },
  {
    value: "other",
    label: "Other Locations",
  },
];

export const invoiceStatusOptions = [
  {
    value: "not_sent",
    label: "Not Sent",
  },
  { value: "scheduled", label: "Scheduled" },
  { value: "paid", label: "Paid" },

  { value: "sent", label: "Sent" },
];

export const candidatesStatuse = [
  {
    value: "application_started",
    label: "Application Started",
  },
  { value: "applied", label: "Applied" },
  { value: "interview_complete", label: "Interview Complete" },
  { value: "profile_complete", label: "Profile Complete" },
];

export const paymentHistoryTableData = [
  {
    id: "1",
    invoices: "GSV567489240UI",
    description: "Cash payment received for job placement service fee",
    amount: "$11,000.00",
    paymentMethod: "Cash",
  },
  {
    id: "2",
    invoices: "GSV567489241UI",
    description: "Manual payment recorded for recruitment subscription plan",
    amount: "$10,800.00",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "3",
    invoices: "GSV567489242UI",
    description: "Check payment received for candidate sourcing services",
    amount: "$37,500.00",
    paymentMethod: "Cheque",
  },
  {
    id: "4",
    invoices: "GSV567489239UI",
    description: "Offline payment collected for premium hiring package",
    amount: "$29,000.00",
    paymentMethod: "Cheque",
  },
  {
    id: "5",
    invoices: "GSV567489242UI",
    description: "Cash payment for monthly employer platform access",
    amount: "$17,500.00",
    paymentMethod: "Cash",
  },
  {
    id: "6",
    invoices: "GSV5674892421UI",
    description: "Manual payment received for featured job listing upgrade",
    amount: "$5,400.00",
    paymentMethod: "Cheque",
  },
  {
    id: "7",
    invoices: "GSV5674892241UI",
    description: "Check payment processed for executive search service",
    amount: "$4,200.00",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "8",
    invoices: "GSV56748941UI",
    description: "Offline payment recorded for talent acquisition consultation",
    amount: "$7,200.00",
    paymentMethod: "Cash",
  },
  {
    id: "9",
    invoices: "GSV567489243UI",
    description: "Cash payment for recruitment campaign management fee",
    amount: "$15,000.00",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "10",
    invoices: "GSV567489241UI",
    description: "Manual payment received for hiring support services",
    amount: "$28,125.00",
    paymentMethod: "Cash",
  },
];

export const advancedInvoiceTableData = [
  {
    id: 1,
    invoiceId: "5833",
    name: "Invoice#",
    invoiceTotal: "$2018.25",
    status: "Scheduled",
    createdAt: "Sat Nov 29 2025 at 14:58:20",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 2,
    invoiceId: "5833",
    name: "Bill sanders",
    invoiceTotal: "$2018.25",
    status: "Scheduled",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 3,
    invoiceId: "5833",
    name: "Georgia young",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 4,
    invoiceId: "5833",
    name: "Jessica hanson",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 5,
    invoiceId: "5833",
    name: "Nathan roberts",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 6,
    invoiceId: "5833",
    name: "Tanya hill",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 7,
    invoiceId: "5833",
    name: "Nathan roberts",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
];

export const PROFILES = [
  {
    id: 1,
    image: "/candidates/candidates.png",
    name: "Cameron Williamson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "House Manager"],
    experience: "08 Years",
    description:
      "I have cared for children from infancy through early adolescence, with a strong passion and focus on early childhood development.",
  },
  {
    id: 2,
    image: "/candidates/candidates-1.png",
    name: "Darrell Steward",
    locations: ["New York", "Miami"],
    roles: ["Nanny", "House Manager"],
    experience: "04 Years",
    description:
      "I have experience providing structured childcare, supporting developmental milestones, and creating engaging, age-appropriate activities.",
  },
  {
    id: 3,
    image: "/candidates/candidates-2.png",
    name: "Darlene Robertson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "Baby/Night Nurse"],
    experience: "05 Years",
    description:
      "I have 8 years of experience as a nanny and house manager, working with children from infancy to school age.",
  },
  {
    id: 4,
    image: "/candidates/candidates.png",
    name: "Darlene Robertson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "Baby/Night Nurse"],
    experience: "05 Years",
    description:
      "I have 8 years of experience as a nanny and house manager, working with children from infancy to school age.",
  },
  {
    id: 5,
    image: "/candidates/candidates-1.png",
    name: "Cameron Williamson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "House Manager"],
    experience: "08 Years",
    description:
      "I have cared for children from infancy through early adolescence, with a strong passion and focus on early childhood development.",
  },
  {
    id: 6,
    image: "/candidates/candidates-2.png",
    name: "Darrell Steward",
    locations: ["New York", "Miami"],
    roles: ["Nanny", "House Manager"],
    experience: "04 Years",
    description:
      "I have experience providing structured childcare, supporting developmental milestones, and creating engaging, age-appropriate activities.",
  },
];

export const currentJobs = [
  {
    id: 1,
    title: "After School Nanny",
    jobType: "Short-term",
    name: "Ariana McCoy",
    avatar: "/candidate/avatar-1.jpg",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "JAN 28, 2025",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "running",
  },
  {
    id: 2,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/candidate/avatar-1.jpg",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "scheduled",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 3,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/candidate/avatar-1.jpg",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 28, 2026",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "completed",
    checkIn: "Mar 28, 2026",
    checkOut: "8:02 PM",
    total: "2h 05m",
  },
];
