import j1 from "@/public/jobImage/j1.png";
import j2 from "@/public/jobImage/j2.png";
import j3 from "@/public/jobImage/j3.png";
import j4 from "@/public/jobImage/j4.png";
import jobImage from "@/public/jobs/Rectangle 856.png";
import { EventInput } from "@fullcalendar/core/index.js";
export const demoData = [
  {
    id: "1",
    full_name: "Leslie Alexander",
    email_address: "felicia.reid@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882918803",
    createdAt: "2014-05-30T00:00:00Z",
    time: "2014-05-30T10:30:00Z",
    additional_information: "Website",
    status: "Pre Application",
    image_name: j1,
  },
  {
    invoiceId: "5833",
    full_name: "Devon Lane",
    email_address: "bill.sanders@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+18102458249",
    createdAt: "2015-05-27T00:00:00Z",
    time: "2015-05-27T14:15:00Z",
    additional_information: "Phone Call",
    status: "Applied",
    image_name: j2,
  },
  {
    id: "3",
    full_name: "Eleanor Pena",
    email_address: "georgia.young@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882918803",
    createdAt: "2012-02-11T00:00:00Z",
    time: "2012-02-11T09:00:00Z",
    additional_information: "Facebook",
    status: "Pre Application",
    image_name: j3,
  },
  {
    id: "4",
    full_name: "Kathryn Murphy",
    email_address: "jessica.hanson@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14884608141",
    createdAt: "2014-01-14T00:00:00Z",
    time: "2014-01-14T16:45:00Z",
    additional_information: "Email",
    status: "Applied",
    image_name: j4,
  },
  {
    id: "5",
    full_name: "Robert Fox",
    email_address: "nathan.roberts@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882634865",
    createdAt: "2014-08-30T00:00:00Z",
    time: "2014-08-30T11:20:00Z",
    additional_information: "WhatsApp",
    status: "Pre Application",
    image_name: j1,
  },
  {
    id: "6",
    full_name: "Ronald Richards",
    email_address: "tanya.hill@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14884145917",
    createdAt: "2016-09-18T00:00:00Z",
    time: "2016-09-18T13:30:00Z",
    additional_information: "Website",
    status: "Pending",
    image_name: j2,
  },
  {
    id: "7",
    full_name: "Bessie Cooper",
    email_address: "kenzi.lawson@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+19143008346",
    createdAt: "2013-12-10T00:00:00Z",
    time: "2013-12-10T08:00:00Z",
    additional_information: "Referral",
    status: "Pre Application",
    image_name: j3,
  },
  {
    id: "8",
    full_name: "Cameron Williamson",
    email_address: "willie.jennings@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14882634869",
    createdAt: "2013-10-08T00:00:00Z",
    time: "2013-10-08T15:45:00Z",
    additional_information: "Instagram",
    status: "Pre Application",
    image_name: j4,
  },
  {
    id: "9",
    full_name: "Wade Warren",
    email_address: "dolores.chambers@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882820363",
    createdAt: "2013-07-27T00:00:00Z",
    time: "2013-07-27T10:30:00Z",
    additional_information: "Email",
    status: "Inactive",
    image_name: j1,
  },
  {
    id: "10",
    full_name: "Ralph Edwards",
    email_address: "nevaeh.simmons@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+18102448985",
    createdAt: "2017-08-16T00:00:00Z",
    time: "2017-08-16T14:20:00Z",
    additional_information: "Website",
    status: "Applied",
    image_name: j4,
  },
  {
    id: "11",
    full_name: "Marvin McKinney",
    email_address: "tim.jennings@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+19143008184",
    createdAt: "2016-09-23T00:00:00Z",
    time: "2016-09-23T09:15:00Z",
    additional_information: "Phone Call",
    status: "Pre Application",
    image_name: j2,
  },
];

export const noteData = [
  {
    id: "1",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "2",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Client",
  },
  {
    id: "3",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "4",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "client",
  },
  {
    id: "5",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "6",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "7",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "8",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "9",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "10",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
  {
    id: "11",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    type: "Candidate",
  },
];

export const documentsData = [
  {
    id: "1",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "2",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "3",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "4",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "5",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "6",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "7",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "8",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "9",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "10",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
  {
    id: "11",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    trigger_status: "Application Approved",
    created_at: "2025-11-12",
    updated_at: "2025-11-12",
  },
];

export const mailTemplateData = [
  {
    id: "1",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    location: "Chicago",
    status: "Application Approved",
  },
  {
    id: "2",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    location: "DC Metro Area",
    status: "Application Approved",
  },
  {
    id: "3",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    location: "DC Metro Area",
    status: "Application Approved",
  },
  {
    id: "4",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    location: "Chicago",
    status: "Application Approved",
  },
  {
    id: "5",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    location: "DC Metro Area",
    status: "Application Approved",
  },
  {
    id: "6",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    location: "DC Metro Area",
    status: "Application Approved",
  },
  {
    id: "7",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "clinet",
    category: "Midwest Elite Nannies",
    location: "lowa",
    status: "Application Approved",
  },
  {
    id: "8",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    location: "DC Metro Area",
    status: "Interview Complete",
  },
  {
    id: "9",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    location: "Chicago",
    status: "Interview Complete",
  },
  {
    id: "10",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    location: "DC Metro Area",
    status: "Application Approved",
  },
  {
    id: "11",
    full_name:
      "Client Application Approved - Access Dashboard and Sign Agreement",
    user_type: "Candidate",
    category: "Midwest Elite Nannies",
    location: "DC Metro Area",
    status: "Interview Complete",
  },
];

export const SuperAdminDashboardData = [
  {
    id: "1",
    agency_name: "TalentBridge Solutions",
    domain: "talentbridge.platform.io",
    revenue: "$1,400",
    client: 230,
    candidate: 1450,
    status: "Active",
    joined: "October 30, 2017",
  },
  {
    id: "2",
    agency_name: "SwiftStaff Agency",
    domain: "swiftstaff.platform.io",
    revenue: null,
    client: 858,
    candidate: 2632,
    status: "Active",
    joined: "August 2, 2013",
  },
  {
    id: "3",
    agency_name: "PeoplePulse HR",
    domain: "peoplepulse.platform.io",
    revenue: null,
    client: 145,
    candidate: 230,
    status: "Suspended",
    joined: "February 11, 2014",
  },
  {
    id: "4",
    agency_name: "NexaRecruit",
    domain: "nexarecruit.platform.io",
    revenue: null,
    client: 58,
    candidate: 122,
    status: "Active",
    joined: "December 29, 2012",
  },
  {
    id: "5",
    agency_name: "StaffMatrix Ltd",
    domain: "staffmatrix.platform.io",
    revenue: null,
    client: 11,
    candidate: 863,
    status: "Inactive",
    joined: "December 2, 2018",
  },
  {
    id: "6",
    agency_name: "Ronald Richards",
    domain: "Doc",
    revenue: null,
    client: 952,
    candidate: 3001,
    status: "Active",
    joined: "May 29, 2017",
  },
  {
    id: "7",
    agency_name: "TalentBridge Solutions",
    domain: "talentbridge.platform.io",
    revenue: null,
    client: 45,
    candidate: 522,
    status: "Active",
    joined: "August 7, 2017",
  },
  {
    id: "8",
    agency_name: "Cameron Williamson",
    domain: "Diki",
    revenue: null,
    client: 80,
    candidate: 300,
    status: "Active",
    joined: "February 29, 2012",
  },
  {
    id: "9",
    agency_name: "SwiftStaff Agency",
    domain: "swiftstaff.platform.io",
    revenue: null,
    client: 41,
    candidate: 890,
    status: "Active",
    joined: "May 8, 2012",
  },
  {
    id: "10",
    agency_name: "RecruitEdge Inc",
    domain: "swiftstaff.platform.io",
    revenue: null,
    client: 77,
    candidate: 952,
    status: "Suspended",
    joined: "October 24, 2018",
  },
];

export const candidateListData = [
  {
    id: "1",
    full_name: "Bessie Cooper",
    email_address: "felicia.reid@example.com",
    mobile_number: "+14842918883",
    position: "Nanny, House Manager",
    last_login: "2024-10-24T08:00:00Z",
    location: "Chicago",
    status: "Application Started",
  },
  {
    invoiceId: "5833",
    full_name: "Marvin McKinney",
    email_address: "bill.sanders@example.com",
    mobile_number: "+16102458249",
    position: "Baby/Night Nurse",
    last_login: "2024-10-24T08:05:00Z",
    location: "Other Locations",
    status: "Applied",
  },
  {
    id: "3",
    full_name: "Brooklyn Simmons",
    email_address: "georgia.young@example.com",
    mobile_number: "+14842918653",
    position: "Nanny",
    last_login: "2024-10-24T08:10:00Z",
    location: "Chicago, DC Metro Area",
    status: "Interview Complete",
  },
  {
    id: "4",
    full_name: "Courtney Henry",
    email_address: "jessica.hanson@example.com",
    mobile_number: "+14844080141",
    position: "Nanny",
    last_login: "2024-10-24T08:15:00Z",
    location: "DC Metro Area, Other Locations",
    status: "Application Started",
  },
  {
    id: "5",
    full_name: "Arlene McCoy",
    email_address: "nathan.roberts@example.com",
    mobile_number: "+14842634655",
    position: "Nurse",
    last_login: "2024-10-24T08:20:00Z",
    location: "DC Metro Area, Other Locations, New York, Chicago",
    status: "Profile Complete",
  },
  {
    id: "6",
    full_name: "Floyd Miles",
    email_address: "tanya.hill@example.com",
    mobile_number: "+14844145917",
    position: "Nanny",
    last_login: "2024-10-24T08:25:00Z",
    location: "Chicago",
    status: "Applied",
  },
  {
    id: "7",
    full_name: "Cody Fisher",
    email_address: "kenzi.lawson@example.com",
    mobile_number: "+18143008346",
    position: "House Manager",
    last_login: "2024-10-24T08:30:00Z",
    location: "Chicago",
    status: "Application Started",
  },
  {
    id: "8",
    full_name: "Jerome Bell",
    email_address: "willie.jennings@example.com",
    mobile_number: "+14842634689",
    position: "Nanny",
    last_login: "2024-10-24T08:35:00Z",
    location: "DC Metro Area, Other Locations",
    status: "Application Started",
  },
  {
    id: "9",
    full_name: "Guy Hawkins",
    email_address: "dolores.chambers@example.com",
    mobile_number: "+15552826353",
    position: "Nanny",
    last_login: "2024-10-24T08:40:00Z",
    location: "Chicago",
    status: "Applied",
  },
  {
    id: "10",
    full_name: "Kristin Watson",
    email_address: "nevaeh.simmons@example.com",
    mobile_number: "+16102449865",
    position: "Nanny, House Manager",
    last_login: "2024-10-24T08:45:00Z",
    location: "DC Metro Area, Other Locations",
    status: "Profile Complete",
  },
  {
    id: "11",
    full_name: "Esther Howard",
    email_address: "tim.jennings@example.com",
    mobile_number: "+18143008184",
    position: "Nanny, House Manager, Baby/Night Nurse",
    last_login: "2024-10-24T08:50:00Z",
    location: "DC Metro Area, Other Locations, New York, Chicago",
    status: "Application Started",
  },
];

export const invoicesData = [
  {
    id: "1",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Cash",
  },
  {
    id: "2",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Bank Transfer",
  },
  {
    id: "3",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Cheque",
  },
  {
    id: "4",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Cheque",
  },
  {
    id: "5",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Bank Transfer",
  },
  {
    id: "6",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Cash",
  },
  {
    id: "7",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Bank Transfer",
  },
  {
    id: "8",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Cheque",
  },
  {
    id: "9",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Cash",
  },
  {
    id: "10",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Bank Transfer",
  },
  {
    id: "11",
    invoices: "GSV567489243UI",
    date_time: "08/01/21 9:02am",
    price: "$15,000.00",
    payment_method: "Cheque",
  },
];

export const broadcastListData = [
  {
    id: "1",
    full_name: "Bessie Cooper",
    email_address: "felicia.reid@example.com",
    mobile_number: "+14842918883",
    registration_date: "2/11/12",
    status: "Application Started",
    action: "View",
  },
  {
    id: "2",
    full_name: "Marvin McKinney",
    email_address: "bill.sanders@example.com",
    mobile_number: "+16102458249",
    registration_date: "2/11/12",
    status: "Applied",
    action: "View",
  },
  {
    id: "3",
    full_name: "Brooklyn Simmons",
    email_address: "georgia.young@example.com",
    mobile_number: "+14842918653",
    registration_date: "2/11/12",
    status: "Interview Complete",
    action: "View",
  },
  {
    id: "4",
    full_name: "Courtney Henry",
    email_address: "jessica.hanson@example.com",
    mobile_number: "+14844080141",
    registration_date: "2/11/12",
    status: "Application Started",
    action: "View",
  },
  {
    id: "5",
    full_name: "Arlene McCoy",
    email_address: "nathan.roberts@example.com",
    mobile_number: "+14842634655",
    registration_date: "2/11/12",
    status: "Profile Complete",
    action: "View",
  },
  {
    id: "6",
    full_name: "Floyd Miles",
    email_address: "tanya.hill@example.com",
    mobile_number: "+14844145917",
    registration_date: "2/11/12",
    status: "Applied",
    action: "View",
  },
  {
    id: "7",
    full_name: "Cody Fisher",
    email_address: "kenzi.lawson@example.com",
    mobile_number: "+18143008346",
    registration_date: "2/11/12",
    status: "Application Started",
    action: "View",
  },
  {
    id: "8",
    full_name: "Jerome Bell",
    email_address: "willie.jennings@example.com",
    mobile_number: "+14842634689",
    registration_date: "2/11/12",
    status: "Application Started",
    action: "View",
  },
  {
    id: "9",
    full_name: "Guy Hawkins",
    email_address: "dolores.chambers@example.com",
    mobile_number: "+15552826353",
    registration_date: "2/11/12",
    status: "Applied",
    action: "View",
  },
  {
    id: "10",
    full_name: "Kristin Watson",
    email_address: "nevaeh.simmons@example.com",
    mobile_number: "+16102449865",
    registration_date: "2/11/12",
    status: "Profile Complete",
    action: "View",
  },
  {
    id: "11",
    full_name: "Esther Howard",
    email_address: "tim.jennings@example.com",
    mobile_number: "+18143008184",
    registration_date: "2/11/12",
    status: "Application Started",
    action: "View",
  },
];

export const applicantsListData = [
  {
    id: "1",
    full_name: "Bessie Cooper",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "2",
    full_name: "Marvin McKinney",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "3",
    full_name: "Brooklyn Simmons",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "4",
    full_name: "Courtney Henry",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "5",
    full_name: "Arlene McCoy",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "6",
    full_name: "Floyd Miles",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "7",
    full_name: "Cody Fisher",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "8",
    full_name: "Jerome Bell",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "9",
    full_name: "Guy Hawkins",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "10",
    full_name: "Kristin Watson",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
  {
    id: "11",
    full_name: "Esther Howard",
    application_date: "15 May 2020 9:00 am",
    status: "Interested",
    application_message:
      "Looking for a dedicated Nanny and House Manager to help keep everything running smoothly at home.",
    action: "Assign Candidate",
  },
];

export const statuse = [
  {
    value: "Pre Application",
    color: "bg-green-500/15 text-green-600",
  },
  {
    value: "Applied",
    color: "bg-purple-500/15 text-purple-600",
  },
  {
    value: "Inactive",
    color: "bg-red-500/15 text-red-600",
  },
  {
    value: "Pending",
    color: "bg-orange-500/15 text-orange-600",
  },
];

export const applicationDateOptions = [
  {
    value: "application_date",
    label: "Application Date",
  },
  {
    value: "last_login",
    label: "Last Login Date",
  },
  {
    value: "recent_access",
    label: "Recent Access",
  },
];

export const typeFilters = [
  {
    value: "midwest_elite_nannies",
    label: "Midwest Elite Nannies",
  },
  {
    value: "admin",
    label: "ADMIN",
  },
  {
    value: "user",
    label: "USER",
  },
];

export const locationFilters = [
  {
    value: "dc_metro",
    label: "DC Metro Area",
  },
  {
    value: "new_york",
    label: "New York",
  },
  {
    value: "miami",
    label: "Miami",
  },
  {
    value: "iowa",
    label: "Iowa",
  },
  {
    value: "other",
    label: "Other Locations",
  },
];

export const invoiceStatusOptions = [
  {
    value: "not_sent",
    label: "Not Sent",
  },
  { value: "scheduled", label: "Scheduled" },
  { value: "paid", label: "Paid" },

  { value: "sent", label: "Sent" },
];

export const candidatesStatuse = [
  {
    value: "application_started",
    label: "Application Started",
  },
  { value: "applied", label: "Applied" },
  { value: "interview_complete", label: "Interview Complete" },
  { value: "profile_complete", label: "Profile Complete" },
];

export const paymentHistoryTableData = [
  {
    id: "1",
    invoices: "GSV567489240UI",
    description: "Cash payment received for job placement service fee",
    amount: "$11,000.00",
    paymentMethod: "Cash",
  },
  {
    id: "2",
    invoices: "GSV567489241UI",
    description: "Manual payment recorded for recruitment subscription plan",
    amount: "$10,800.00",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "3",
    invoices: "GSV567489242UI",
    description: "Check payment received for candidate sourcing services",
    amount: "$37,500.00",
    paymentMethod: "Cheque",
  },
  {
    id: "4",
    invoices: "GSV567489239UI",
    description: "Offline payment collected for premium hiring package",
    amount: "$29,000.00",
    paymentMethod: "Cheque",
  },
  {
    id: "5",
    invoices: "GSV567489242UI",
    description: "Cash payment for monthly employer platform access",
    amount: "$17,500.00",
    paymentMethod: "Cash",
  },
  {
    id: "6",
    invoices: "GSV5674892421UI",
    description: "Manual payment received for featured job listing upgrade",
    amount: "$5,400.00",
    paymentMethod: "Cheque",
  },
  {
    id: "7",
    invoices: "GSV5674892241UI",
    description: "Check payment processed for executive search service",
    amount: "$4,200.00",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "8",
    invoices: "GSV56748941UI",
    description: "Offline payment recorded for talent acquisition consultation",
    amount: "$7,200.00",
    paymentMethod: "Cash",
  },
  {
    id: "9",
    invoices: "GSV567489243UI",
    description: "Cash payment for recruitment campaign management fee",
    amount: "$15,000.00",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "10",
    invoices: "GSV567489241UI",
    description: "Manual payment received for hiring support services",
    amount: "$28,125.00",
    paymentMethod: "Cash",
  },
];

export const advancedInvoiceTableData = [
  {
    id: 1,
    invoiceId: "5833",
    name: "Invoice#",
    invoiceTotal: "$2018.25",
    status: "Scheduled",
    createdAt: "Sat Nov 29 2025 at 14:58:20",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 2,
    invoiceId: "5833",
    name: "Bill sanders",
    invoiceTotal: "$2018.25",
    status: "Scheduled",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 3,
    invoiceId: "5833",
    name: "Georgia young",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 4,
    invoiceId: "5833",
    name: "Jessica hanson",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 5,
    invoiceId: "5833",
    name: "Nathan roberts",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 6,
    invoiceId: "5833",
    name: "Tanya hill",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
  {
    id: 7,
    invoiceId: "5833",
    name: "Nathan roberts",
    invoiceTotal: "$2018.25",
    status: "Paid",
    createdAt: "Sat Nov 29 2025 at 15:27:14",
    dueDate: "Tue Dec 30 2025",
  },
];

export const PROFILES = [
  {
    id: 1,
    image: "/candidates/candidates.png",
    name: "Cameron Williamson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "House Manager"],
    experience: "08 Years",
    description:
      "I have cared for children from infancy through early adolescence, with a strong passion and focus on early childhood development.",
    status: "under-consideration",
    linked: "Mon Nov 18 2024 at 21 46 04",
    clientInterviewPrefeRence: "In person",
    clientInterviewAvailability: "Any time after 5pm on 11/18,11/19,11/20",
  },
  {
    id: 2,
    image: "/candidates/candidates-1.png",
    name: "Darrell Steward",
    locations: ["New York", "Miami"],
    roles: ["Nanny", "House Manager"],
    experience: "04 Years",
    description:
      "I have experience providing structured childcare, supporting developmental milestones, and creating engaging, age-appropriate activities.",
    status: "under-consideration",
    linked: "Mon Nov 18 2024 at 21 46 04",
  },
  {
    id: 3,
    image: "/candidates/candidates-2.png",
    name: "Darlene Robertson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "Baby/Night Nurse"],
    experience: "05 Years",
    description:
      "I have 8 years of experience as a nanny and house manager, working with children from infancy to school age.",
    status: "not-interested",
    linked: "Mon Nov 18 2024 at 21 46 04",
    notes:
      "I think Nakita could be a good personality fit and would create a really positive dynamic With the girls. She is open to travel, but would prefer not for 4 full consecutive weeks.",
  },
  {
    id: 4,
    image: "/candidates/candidates.png",
    name: "Darlene Robertson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "Baby/Night Nurse"],
    experience: "05 Years",
    description:
      "I have 8 years of experience as a nanny and house manager, working with children from infancy to school age.",
    status: "not-interested",
    linked: "Mon Nov 18 2024 at 21 46 04",
  },
  {
    id: 5,
    image: "/candidates/candidates-1.png",
    name: "Cameron Williamson",
    locations: ["Miami", "New York", "Other Locations"],
    roles: ["Nanny", "House Manager"],
    experience: "08 Years",
    description:
      "I have cared for children from infancy through early adolescence, with a strong passion and focus on early childhood development.",
    status: "interested",
    linked: "Mon Nov 18 2024 at 21 46 04",
    notes: "Kelsey is targeting an August start date.",
  },
  {
    id: 6,
    image: "/candidates/candidates-2.png",
    name: "Darrell Steward",
    locations: ["New York", "Miami"],
    roles: ["Nanny", "House Manager"],
    experience: "04 Years",
    description:
      "I have experience providing structured childcare, supporting developmental milestones, and creating engaging, age-appropriate activities.",
    status: "under-consideration",
    linked: "Mon Nov 18 2024 at 21 46 04",
  },
];

export const clientCurrentJobs = [
  {
    id: 1,
    title: "After School Nanny",
    jobType: "Short-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j1.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "JAN 28, 2025",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    hourlyRate: "$35/hr",
    status: "running",
  },
  {
    id: 2,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "pending",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 3,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j3.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 28, 2026",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "marketplace",
    checkIn: "Mar 28, 2026",
    checkOut: "8:02 PM",
    total: "2h 05m",
  },
  {
    id: 4,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "completed",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 5,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "canceled",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 6,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "08:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "rejected",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
];

export const adminCurrentJobs = [
  {
    id: 1,
    title: "After School Nanny",
    jobType: "Short-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j1.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "JAN 28, 2025",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    hourlyRate: "$35/hr",
    status: "running",
  },
  {
    id: 2,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "pending",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 3,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j3.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 28, 2026",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "marketplace",
    checkIn: "Mar 28, 2026",
    checkOut: "8:02 PM",
    total: "2h 05m",
  },
  {
    id: 4,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "completed",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 5,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "canceled",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 6,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "08:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "rejected",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
];

export const currentJobs = [
  {
    id: 1,
    title: "After School Nanny",
    jobType: "Short-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j1.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "JAN 28, 2025",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "running",
  },
  {
    id: 2,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j2.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 08, 2026",
    endDate: "Mar 07, 2026",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "cancel",
    checkOut: "8:02 PM",
    checkIn: "8:00 AM",
    total: "12h 02m",
  },
  {
    id: 3,
    title: "After School Nanny",
    jobType: "Long-term",
    name: "Ariana McCoy",
    avatar: "/jobImage/j3.png",
    description:
      "Full responsibility for three energetic children, ages 5, 6, and 7, including crafting delicious and...",
    location: "71 Raglan Street, CROWNTHORP, Queensville(QLO), 4805",
    startDate: "Mar 28, 2026",
    endDate: "FEB 26, 2025",
    startTime: "10:00AM",
    endTime: "11:00PM",
    hourlyRate: "$35/hr",
    status: "completed",
    checkIn: "Mar 28, 2026",
    checkOut: "8:02 PM",
    total: "2h 05m",
  },
];

const currentDate = new Date();
const currentYear = currentDate.getFullYear();
const currentMonth = String(currentDate.getMonth() + 1).padStart(2, "0");
const toCurrentMonthDate = (day: number) =>
  `${currentYear}-${currentMonth}-${String(day).padStart(2, "0")}`;

export const jobEvents: EventInput[] = [
  {
    id: "1",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(1),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "2",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(2),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "3",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(3),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "4",
    title: "Jacob Jones",
    start: toCurrentMonthDate(4),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "5",
    title: "Courtney He...",
    start: toCurrentMonthDate(3),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "6",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(7),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "7",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(8),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "8",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(9),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "9",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(10),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "10",
    title: "Jacob Jones",
    start: toCurrentMonthDate(10),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "11",
    title: "Courtney He...",
    start: toCurrentMonthDate(11),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "12",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "13",
    title: "Jacob Jones",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "14",
    title: "Courtney He...",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "15",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "16",
    title: "Jacob Jones",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "17",
    title: "Courtney He...",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "18",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "19",
    title: "Jacob Jones",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "20",
    title: "Courtney He...",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "21",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(23),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "22",
    title: "Jacob Jones",
    start: toCurrentMonthDate(23),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "23",
    title: "Courtney He...",
    start: toCurrentMonthDate(24),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "24",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(30),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "25",
    title: "Jacob Jones",
    start: toCurrentMonthDate(31),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "26",
    title: "Courtney He...",
    start: toCurrentMonthDate(31),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
];

export const interviewEvents: EventInput[] = [
  {
    id: "1",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(1),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "2",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(2),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "3",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(3),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "4",
    title: "Jacob Jones",
    start: toCurrentMonthDate(4),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "5",
    title: "Courtney He...",
    start: toCurrentMonthDate(3),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "6",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(7),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "7",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(8),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "8",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(9),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "9",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(10),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "10",
    title: "Jacob Jones",
    start: toCurrentMonthDate(10),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "11",
    title: "Courtney He...",
    start: toCurrentMonthDate(11),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "12",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "13",
    title: "Jacob Jones",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "14",
    title: "Courtney He...",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "15",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "16",
    title: "Jacob Jones",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "17",
    title: "Courtney He...",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "18",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "19",
    title: "Jacob Jones",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "20",
    title: "Courtney He...",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "21",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(23),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "22",
    title: "Jacob Jones",
    start: toCurrentMonthDate(23),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "23",
    title: "Courtney He...",
    start: toCurrentMonthDate(24),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "24",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(30),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "25",
    title: "Jacob Jones",
    start: toCurrentMonthDate(31),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "26",
    title: "Courtney He...",
    start: toCurrentMonthDate(31),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "27",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(5),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#FF3D49", jobTime: "3:25 pm" },
  },
  {
    id: "28",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(6),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#E5B400", jobTime: "3:25 pm" },
  },
  {
    id: "29",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(12),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#2B7FFF", jobTime: "3:25 pm" },
  },
];

export const shortTermJobEvents: EventInput[] = [
  {
    id: "1",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(1),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "2",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(2),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "3",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(3),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "4",
    title: "Jacob Jones",
    start: toCurrentMonthDate(4),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "5",
    title: "Courtney He...",
    start: toCurrentMonthDate(3),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "6",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(7),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "7",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(8),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "8",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(9),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "9",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(10),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "10",
    title: "Jacob Jones",
    start: toCurrentMonthDate(10),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "11",
    title: "Courtney He...",
    start: toCurrentMonthDate(11),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "12",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "13",
    title: "Jacob Jones",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "14",
    title: "Courtney He...",
    start: toCurrentMonthDate(14),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "15",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "16",
    title: "Jacob Jones",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "17",
    title: "Courtney He...",
    start: toCurrentMonthDate(17),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "18",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "19",
    title: "Jacob Jones",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "20",
    title: "Courtney He...",
    start: toCurrentMonthDate(21),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "21",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(23),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "22",
    title: "Jacob Jones",
    start: toCurrentMonthDate(23),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "23",
    title: "Courtney He...",
    start: toCurrentMonthDate(24),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "24",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(30),
    allDay: true,
    extendedProps: { type: "long", dotColor: "#3B82F6", jobTime: "3:35 pm" },
  },
  {
    id: "25",
    title: "Jacob Jones",
    start: toCurrentMonthDate(31),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "4:23 pm" },
  },
  {
    id: "26",
    title: "Courtney He...",
    start: toCurrentMonthDate(31),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#16A34A", jobTime: "3:25 pm" },
  },
  {
    id: "27",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(5),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#FF3D49", jobTime: "3:25 pm" },
  },
  {
    id: "28",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(6),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#E5B400", jobTime: "3:25 pm" },
  },
  {
    id: "29",
    title: "Darlene Rob...",
    start: toCurrentMonthDate(12),
    allDay: true,
    extendedProps: { type: "short", dotColor: "#2B7FFF", jobTime: "3:25 pm" },
  },
];

export const jobs = [
  {
    id: 1,
    candidateName: "Darlene Robertson",
    position: "Nanny",
    roles: ["House Manager", "Baby/Night Nurse"],
    price: "$34/hr",
    location: "Miami, New York, Other Locations",
    status: "Pending",
    start: "Mar 28, 2026",
    image: jobImage,
  },
  {
    id: 2,
    candidateName: "Darlene Robertson",
    position: "Nanny",
    roles: ["House Manager", "Baby/Night Nurse"],
    price: "$34/hr",
    location: "Miami, New York, Other Locations",
    status: "Pending",
    start: "Mar 28, 2026",
    image: jobImage,
  },
];
